In [1]:
import requests
from bs4 import BeautifulSoup


url="https://www.statbunker.com/alltimestats/AllTimeLeagueTable?comp_code=EPL"
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')  # specify 'html.parser' as the parser
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <title>
   All time - League Table Premier League
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <meta content="see all time - league table for premier league, football stats from statbunker" name="description"/>
  <meta content="All time - League Table Premier League" property="og:title"/>
  <meta content="Statbunker football" property="og:site_name"/>
  <meta content="https://www.statbunker.com/" property="og:url"/>
  <meta content="see all time - league table for premier league, football stats from statbunker" property="og:description"/>
  <meta content="https://www.statbunker.com/images/footballstats.png" property="og:image"/>
  <meta content="The most up to date football stats on the web!" name="twitter:card"/>
  <meta content="https://www.statbunker.com/" name="twitter:url"/>
  <meta content="All time - League Table Premier League" name="twitter:title"/>
  <meta content="see all time - league table for premier league, football stats from statbunker" name="twitter:description"/>
  <meta content="https://www.statbunker.com/images/footballstats.png" name="twitter:image"/>
  <meta content="app-id=1117368374" name="apple-itunes-app"/>
  <meta content="app-id=com.statbunker.football" name="google-play-app"/>
  <link href="/images/favicon.ico" rel="shortcut icon" type="image/ico"/>
  <link href="https://www.statbunker.com/css/screen.min.css" rel="stylesheet" type="text/css"/>
  <link href="https://www.statbunker.com/css/mobile.css" rel="stylesheet" type="text/css"/>
  <link href="https://www.statbunker.com/css/fix.css" rel="stylesheet" type="text/css"/>
  <link href="https://www.statbunker.com/css/elastislide.min.css" rel="stylesheet" type="text/css"/>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css"/>
  <script src="https://www.statbunker.com/js/jquery-1.11.1.min.js" type="text/javascript">
  </script>
  <link href="https://www.statbunker.com/alltimestats/AllTimeLeagueTable?comp_code=EPL" rel="canonical"/>
  <link href="/js/smartbanner/jquery.smartbanner.css" media="screen" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <header id="main">
   <p class="overlay">
   </p>
   <div class="overlay">
   </div>
   <img alt="Show Menu" src="/images/mobMenuShow.png"/>
   <a href="/">
    <img alt="Logo" height="39" id="logo" src="https://www.statbunker.com/images/logo.png" width="245"/>
   </a>
   <nav id="mainNav">
    <ul class="nav">
     <li>
      <a href="https://www.statbunker.com/">
       Competitions
      </a>
     </li>
     <li class="navActive">
      <a href="https://www.statbunker.com/alltimestats">
       All time stats
      </a>
     </li>
     <li>
      <a href="https://www.statbunker.com/managers">
       Managers
      </a>
     </li>
    </ul>
   </nav>
   <div class="con">
    <form action="https://www.statbunker.com/usual/search" id="navForm" method="get">
     <input name="action" type="hidden" value="Find"/>
     <input class="wdth_small" name="search" placeholder="Players, clubs or managers" type="text" value=""/>
     <button class="submit">
      <img alt="Search" height="32" src="https://www.statbunker.com/images/search.png" width="32"/>
     </button>
    </form>
   </div>
  </header>
  <div id="clubList">
   <link href="https://www.statbunker.com/css/elastislide.min.css" rel="stylesheet" type="text/css"/>
   <h2>
    All Time Club Statistics for Premier League
   </h2>
   <ul class="elastislide-list" id="carousel">
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=111" title="AFC Bournemouth All time - Leading Scorers all time stats for Premier League">
      <img alt="AFC Bournemouth" height="98" src="/img/players_shirt/custom/111.png" title="AFC Bournemouth All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        AFC Bournemouth
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=5" title="Arsenal All time - Leading Scorers all time stats for Premier League">
      <img alt="Arsenal" height="98" src="/img/players_shirt/custom/5.png" title="Arsenal All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Arsenal
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=24" title="Aston Villa All time - Leading Scorers all time stats for Premier League">
      <img alt="Aston Villa" height="98" src="/img/players_shirt/custom/24.png" title="Aston Villa All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Aston Villa
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=26" title="Barnsley All time - Leading Scorers all time stats for Premier League">
      <img alt="Barnsley" height="98" src="/img/players_shirt/custom/26.png" title="Barnsley All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Barnsley
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=48" title="Birmingham City All time - Leading Scorers all time stats for Premier League">
      <img alt="Birmingham City" height="98" src="/img/players_shirt/custom/48.png" title="Birmingham City All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Birmingham City
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=34" title="Blackburn Rovers All time - Leading Scorers all time stats for Premier League">
      <img alt="Blackburn Rovers" height="98" src="/img/players_shirt/custom/34.png" title="Blackburn Rovers All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Blackburn Rovers
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=189" title="Blackpool All time - Leading Scorers all time stats for Premier League">
      <img alt="Blackpool" height="98" src="/img/players_shirt/custom/189.png" title="Blackpool All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Blackpool
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=29" title="Bolton Wanderers All time - Leading Scorers all time stats for Premier League">
      <img alt="Bolton Wanderers" height="98" src="/img/players_shirt/custom/29.png" title="Bolton Wanderers All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Bolton Wanderers
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=6" title="Bradford City All time - Leading Scorers all time stats for Premier League">
      <img alt="Bradford City" height="98" src="/img/players_shirt/custom/6.png" title="Bradford City All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Bradford City
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=84" title="Brentford All time - Leading Scorers all time stats for Premier League">
      <img alt="Brentford" height="98" src="/img/players_shirt/custom/84.png" title="Brentford All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Brentford
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=749" title="Brighton &amp; Hove Albion All time - Leading Scorers all time stats for Premier League">
      <img alt="Brighton &amp; Hove Albion" height="98" src="/img/players_shirt/custom/749.png" title="Brighton &amp; Hove Albion All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Brighton &amp; Hove Albion
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=54" title="Burnley All time - Leading Scorers all time stats for Premier League">
      <img alt="Burnley" height="98" src="/img/players_shirt/custom/54.png" title="Burnley All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Burnley
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=108" title="Cardiff City All time - Leading Scorers all time stats for Premier League">
      <img alt="Cardiff City" height="98" src="/img/players_shirt/custom/108.png" title="Cardiff City All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Cardiff City
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=7" title="Charlton Athletic All time - Leading Scorers all time stats for Premier League">
      <img alt="Charlton Athletic" height="98" src="/img/players_shirt/custom/7.png" title="Charlton Athletic All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Charlton Athletic
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=8" title="Chelsea All time - Leading Scorers all time stats for Premier League">
      <img alt="Chelsea" height="98" src="/img/players_shirt/custom/8.png" title="Chelsea All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Chelsea
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=25" title="Coventry City All time - Leading Scorers all time stats for Premier League">
      <img alt="Coventry City" height="98" src="/img/players_shirt/custom/25.png" title="Coventry City All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Coventry City
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=35" title="Crystal Palace All time - Leading Scorers all time stats for Premier League">
      <img alt="Crystal Palace" height="98" src="/img/players_shirt/custom/35.png" title="Crystal Palace All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Crystal Palace
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=9" title="Derby County All time - Leading Scorers all time stats for Premier League">
      <img alt="Derby County" height="98" src="/img/players_shirt/custom/9.png" title="Derby County All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Derby County
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=10" title="Everton All time - Leading Scorers all time stats for Premier League">
      <img alt="Everton" height="98" src="/img/players_shirt/custom/10.png" title="Everton All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Everton
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=55" title="Fulham All time - Leading Scorers all time stats for Premier League">
      <img alt="Fulham" height="98" src="/img/players_shirt/custom/55.png" title="Fulham All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Fulham
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=58" title="Huddersfield Town All time - Leading Scorers all time stats for Premier League">
      <img alt="Huddersfield Town" height="98" src="/img/players_shirt/custom/58.png" title="Huddersfield Town All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Huddersfield Town
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=752" title="Hull City All time - Leading Scorers all time stats for Premier League">
      <img alt="Hull City" height="98" src="/img/players_shirt/custom/752.png" title="Hull City All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Hull City
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=11" title="Ipswich Town All time - Leading Scorers all time stats for Premier League">
      <img alt="Ipswich Town" height="98" src="/img/players_shirt/custom/11.png" title="Ipswich Town All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Ipswich Town
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=12" title="Leeds United All time - Leading Scorers all time stats for Premier League">
      <img alt="Leeds United" height="98" src="/img/players_shirt/custom/12.png" title="Leeds United All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Leeds United
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=13" title="Leicester City All time - Leading Scorers all time stats for Premier League">
      <img alt="Leicester City" height="98" src="/img/players_shirt/custom/13.png" title="Leicester City All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Leicester City
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=4" title="Liverpool All time - Leading Scorers all time stats for Premier League">
      <img alt="Liverpool" height="98" src="/img/players_shirt/custom/4.png" title="Liverpool All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Liverpool
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=184" title="Luton Town All time - Leading Scorers all time stats for Premier League">
      <img alt="Luton Town" height="98" src="/img/players_shirt/custom/184.png" title="Luton Town All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Luton Town
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=14" title="Manchester City All time - Leading Scorers all time stats for Premier League">
      <img alt="Manchester City" height="98" src="/img/players_shirt/custom/14.png" title="Manchester City All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Manchester City
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=3" title="Manchester United All time - Leading Scorers all time stats for Premier League">
      <img alt="Manchester United" height="98" src="/img/players_shirt/custom/3.png" title="Manchester United All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Manchester United
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=15" title="Middlesbrough All time - Leading Scorers all time stats for Premier League">
      <img alt="Middlesbrough" height="98" src="/img/players_shirt/custom/15.png" title="Middlesbrough All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Middlesbrough
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=22" title="Milton Keynes Dons All time - Leading Scorers all time stats for Premier League">
      <img alt="Milton Keynes Dons" height="98" src="/img/players_shirt/custom/22.png" title="Milton Keynes Dons All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Milton Keynes Dons
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=16" title="Newcastle United All time - Leading Scorers all time stats for Premier League">
      <img alt="Newcastle United" height="98" src="/img/players_shirt/custom/16.png" title="Newcastle United All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Newcastle United
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=31" title="Norwich City All time - Leading Scorers all time stats for Premier League">
      <img alt="Norwich City" height="98" src="/img/players_shirt/custom/31.png" title="Norwich City All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Norwich City
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=28" title="Nottingham Forest All time - Leading Scorers all time stats for Premier League">
      <img alt="Nottingham Forest" height="98" src="/img/players_shirt/custom/28.png" title="Nottingham Forest All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Nottingham Forest
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=32" title="Oldham Athletic All time - Leading Scorers all time stats for Premier League">
      <img alt="Oldham Athletic" height="98" src="/img/players_shirt/custom/32.png" title="Oldham Athletic All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Oldham Athletic
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=59" title="Portsmouth All time - Leading Scorers all time stats for Premier League">
      <img alt="Portsmouth" height="98" src="/img/players_shirt/custom/59.png" title="Portsmouth All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Portsmouth
       </p>
      </div>
     </a>
    </li>
    <li>
     <a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=30" title="Queens Park Rangers All time - Leading Scorers all time stats for Premier League">
      <img alt="Queens Park Rangers" height="98" src="/img/players_shirt/custom/30.png" title="Queens Park Rangers All time - Leading Scorers all time stats for Premier League" width="120"/>
      <div>
       <p>
        Queens Park Rangers
       </p>
      </div>
     </a>

In [2]:
soup.find('table')

<table class="table">
<caption><h1>Premier League All time - League Table</h1></caption> <thead>
<tr>
<th class="mob">#</th>
<th class="mob">Clubs</th>
<th class="mob" title="Matches played">P</th>
<th class="nonMob" title="Matches won">W</th>
<th class="nonMob" title="Matches drawn">D</th>
<th class="nonMob" title="Matches lost">L</th>
<th class="nonMob" title="Goals for">F</th>
<th class="nonMob" title="Goals against">A</th>
<th class="mob" title="Goal difference">GD</th>
<th class="mob">Points</th>
<th class="nonMob">Wins%</th><th class="nonMob">Points/Match</th> <th class="mob all">More</th>
</tr>
</thead>
<tbody>

In [3]:

titles=soup.find_all('th')
titles

[<th class="mob">#</th>,
 <th class="mob">Clubs</th>,
 <th class="mob" title="Matches played">P</th>,
 <th class="nonMob" title="Matches won">W</th>,
 <th class="nonMob" title="Matches drawn">D</th>,
 <th class="nonMob" title="Matches lost">L</th>,
 <th class="nonMob" title="Goals for">F</th>,
 <th class="nonMob" title="Goals against">A</th>,
 <th class="mob" title="Goal difference">GD</th>,
 <th class="mob">Points</th>,
 <th class="nonMob">Wins%</th>,
 <th class="nonMob">Points/Match</th>,
 <th class="mob all">More</th>]

In [4]:

table_titles=[info.text.strip() for info in titles[0:12]]
table_titles

['#',
 'Clubs',
 'P',
 'W',
 'D',
 'L',
 'F',
 'A',
 'GD',
 'Points',
 'Wins%',
 'Points/Match']

In [5]:
import pandas as pd
df=pd.DataFrame(columns=table_titles)
df

C:\Users\mines\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\mines\AppData\Roaming\Python\Python39\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

Empty DataFrame
Columns: [#, Clubs, P, W, D, L, F, A, GD, Points, Wins%, Points/Match]
Index: []

In [6]:
rows=soup.find_all('tr')
rows

[<tr>
 <th class="mob">#</th>
 <th class="mob">Clubs</th>
 <th class="mob" title="Matches played">P</th>
 <th class="nonMob" title="Matches won">W</th>
 <th class="nonMob" title="Matches drawn">D</th>
 <th class="nonMob" title="Matches lost">L</th>
 <th class="nonMob" title="Goals for">F</th>
 <th class="nonMob" title="Goals against">A</th>
 <th class="mob" title="Goal difference">GD</th>
 <th class="mob">Points</th>
 <th class="nonMob">Wins%</th><th class="nonMob">Points/Match</th> <th class="mob all">More</th>
 </tr>,
 <tr><td class="mob">1</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=3" title="Manchester United All time - Leading Scorers all time stats for Premier League"><img alt="Manchester United" height="23" src="/img/players_shirt/small/3.png" title="Manchester United All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Manchester United</p></div></a></td><td class="mob">1225</td><td class="nonMob">742</td><td class="nonMob">269</td><td class="nonMob">214</td><td class="nonMob">2295</td><td class="nonMob">1164</td><td class="mob">1131</td><td class="mob">2495</td><td class="nonMob">61%</td><td class="nonMob">2.04</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">2</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=5" title="Arsenal All time - Leading Scorers all time stats for Premier League"><img alt="Arsenal" height="23" src="/img/players_shirt/small/5.png" title="Arsenal All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Arsenal</p></div></a></td><td class="mob">1226</td><td class="nonMob">671</td><td class="nonMob">295</td><td class="nonMob">260</td><td class="nonMob">2193</td><td class="nonMob">1219</td><td class="mob">974</td><td class="mob">2308</td><td class="nonMob">55%</td><td class="nonMob">1.88</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">3</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=4" title="Liverpool All time - Leading Scorers all time stats for Premier League"><img alt="Liverpool" height="23" src="/img/players_shirt/small/4.png" title="Liverpool All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Liverpool</p></div></a></td><td class="mob">1226</td><td class="nonMob">651</td><td class="nonMob">301</td><td class="nonMob">274</td><td class="nonMob">2177</td><td class="nonMob">1232</td><td class="mob">945</td><td class="mob">2254</td><td class="nonMob">53%</td><td class="nonMob">1.84</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">4</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=8" title="Chelsea All time - Leading Scorers all time stats for Premier League"><img alt="Chelsea" height="23" src="/img/players_shirt/small/8.png" title="Chelsea All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Chelsea</p></div></a></td><td class="mob">1225</td><td class="nonMob">644</td><td class="nonMob">304</td><td class="nonMob">277</td><td class="nonMob">2081</td><td class="nonMob">1231</td><td class="mob">850</td><td class="mob">2236</td><td class="nonMob">53%</td><td class="nonMob">1.83</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">5</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=19" title="Tottenham Hotspur All time - Leading Scorers all time stats for Premier League"><img alt="Tottenham Hotspur" height="23" src="/img/players_shirt/small/19.png" title="Tottenham Hotspur All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Tottenham Hotspur</p></div></a></td><td class="mob">1225</td><td class="nonMob">538</td><td class="nonMob">293</td><td class="nonMob">394</td><td class="nonMob">1884</td><td class="nonMob">1559</td><td class="mob">325</td><td class="mob">1907</td><td class="nonMob">44%</td><td class="nonMob">1.56</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">6</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=14" title="Manchester City All time - Leading Scorers all time stats for Premier League"><img alt="Manchester City" height="23" src="/img/players_shirt/small/14.png" title="Manchester City All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Manchester City</p></div></a></td><td class="mob">1035</td><td class="nonMob">526</td><td class="nonMob">222</td><td class="nonMob">287</td><td class="nonMob">1839</td><td class="nonMob">1134</td><td class="mob">705</td><td class="mob">1800</td><td class="nonMob">51%</td><td class="nonMob">1.74</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">7</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=10" title="Everton All time - Leading Scorers all time stats for Premier League"><img alt="Everton" height="23" src="/img/players_shirt/small/10.png" title="Everton All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Everton</p></div></a></td><td class="mob">1226</td><td class="nonMob">438</td><td class="nonMob">341</td><td class="nonMob">447</td><td class="nonMob">1563</td><td class="nonMob">1587</td><td class="mob">-24</td><td class="mob">1647</td><td class="nonMob">36%</td><td class="nonMob">1.34</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">8</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=16" title="Newcastle United All time - Leading Scorers all time stats for Premier League"><img alt="Newcastle United" height="23" src="/img/players_shirt/small/16.png" title="Newcastle United All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Newcastle United</p></div></a></td><td class="mob">1107</td><td class="nonMob">418</td><td class="nonMob">283</td><td class="nonMob">406</td><td class="nonMob">1523</td><td class="nonMob">1506</td><td class="mob">17</td><td class="mob">1537</td><td class="nonMob">38%</td><td class="nonMob">1.39</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">9</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=24" title="Aston Villa All time - Leading Scorers all time stats for Premier League"><img alt="Aston Villa" height="23" src="/img/players_shirt/small/24.png" title="Aston Villa All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Aston Villa</p></div></a></td><td class="mob">1112</td><td class="nonMob">392</td><td class="nonMob">310</td><td class="nonMob">410</td><td class="nonMob">1389</td><td class="nonMob">1452</td><td class="mob">-63</td><td class="mob">1486</td><td class="nonMob">35%</td><td class="nonMob">1.34</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">10</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=21" title="West Ham United All time - Leading Scorers all time stats for Premier League"><img alt="West Ham United" height="23" src="/img/players_shirt/small/21.png" title="West Ham United All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>West Ham United</p></div></a></td><td class="mob">1070</td><td class="nonMob">359</td><td class="nonMob">270</td><td class="nonMob">441</td><td class="nonMob">1333</td><td class="nonMob">1554</td><td class="mob">-221</td><td class="mob">1347</td><td class="nonMob">34%</td><td class="nonMob">1.26</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">11</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=18" title="Southampton All time - Leading Scorers all time stats for Premier League"><img alt="Southampton" height="23" src="/img/players_shirt/small/18.png" title="Southampton All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Southampton</p></div></a></td><td class="mob">924</td><td class="nonMob">280</td><td class="nonMob">248</td><td class="nonMob">396</td><td class="nonMob">1114</td><td class="nonMob">1355</td><td class="mob">-241</td><td class="mob">1088</td><td class="nonMob">30%</td><td class="nonMob">1.18</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">12</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=34" title="Blackburn Rovers All time - Leading Scorers all time stats for Premier League"><img alt="Blackburn Rovers" height="23" src="/img/players_shirt/small/34.png" title="Blackburn Rovers All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Blackburn Rovers</p></div></a></td><td class="mob">696</td><td class="nonMob">262</td><td class="nonMob">184</td><td class="nonMob">250</td><td class="nonMob">927</td><td class="nonMob">907</td><td class="mob">20</td><td class="mob">970</td><td class="nonMob">38%</td><td class="nonMob">1.39</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">13</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=13" title="Leicester City All time - Leading Scorers all time stats for Premier League"><img alt="Leicester City" height="23" src="/img/players_shirt/small/13.png" title="Leicester City All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Leicester City</p></div></a></td><td class="mob">650</td><td class="nonMob">218</td><td class="nonMob">167</td><td class="nonMob">265</td><td class="nonMob">871</td><td class="nonMob">936</td><td class="mob">-65</td><td class="mob">821</td><td class="nonMob">34%</td><td class="nonMob">1.26</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">14</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=12" title="Leeds United All time - Leading Scorers all time stats for Premier League"><img alt="Leeds United" height="23" src="/img/players_shirt/small/12.png" title="Leeds United All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Leeds United</p></div></a></td><td class="mob">582</td><td class="nonMob">223</td><td class="nonMob">151</td><td class="nonMob">208</td><td class="nonMob">793</td><td class="nonMob">784</td><td class="mob">9</td><td class="mob">820</td><td class="nonMob">38%</td><td class="nonMob">1.41</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">15</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=55" title="Fulham All time - Leading Scorers all time stats for Premier League"><img alt="Fulham" height="23" src="/img/players_shirt/small/55.png" title="Fulham All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Fulham</p></div></a></td><td class="mob">644</td><td class="nonMob">189</td><td class="nonMob">169</td><td class="nonMob">286</td><td class="nonMob">737</td><td class="nonMob">939</td><td class="mob">-202</td><td class="mob">736</td><td class="nonMob">29%</td><td class="nonMob">1.14</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">16</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=15" title="Middlesbrough All time - Leading Scorers all time stats for Premier League"><img alt="Middlesbrough" height="23" src="/img/players_shirt/small/15.png" title="Middlesbrough All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Middlesbrough</p></div></a></td><td class="mob">574</td><td class="nonMob">165</td><td class="nonMob">169</td><td class="nonMob">240</td><td class="nonMob">648</td><td class="nonMob">794</td><td class="mob">-146</td><td class="mob">661</td><td class="nonMob">29%</td><td class="nonMob">1.15</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">17</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=35" title="Crystal Palace All time - Leading Scorers all time stats for Premier League"><img alt="Crystal Palace" height="23" src="/img/players_shirt/small/35.png" title="Crystal Palace All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Crystal Palace</p></div></a></td><td class="mob">576</td><td class="nonMob">167</td><td class="nonMob">151</td><td class="nonMob">258</td><td class="nonMob">636</td><td class="nonMob">832</td><td class="mob">-196</td><td class="mob">652</td><td class="nonMob">29%</td><td class="nonMob">1.13</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">18</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=23" title="Sunderland All time - Leading Scorers all time stats for Premier League"><img alt="Sunderland" height="23" src="/img/players_shirt/small/23.png" title="Sunderland All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Sunderland</p></div></a></td><td class="mob">608</td><td class="nonMob">153</td><td class="nonMob">159</td><td class="nonMob">296</td><td class="nonMob">612</td><td class="nonMob">904</td><td class="mob">-292</td><td class="mob">618</td><td class="nonMob">25%</td><td class="nonMob">1.02</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">19</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=29" title="Bolton Wanderers All time - Leading Scorers all time stats for Premier League"><img alt="Bolton Wanderers" height="23" src="/img/players_shirt/small/29.png" title="Bolton Wanderers All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Bolton Wanderers</p></div></a></td><td class="mob">494</td><td class="nonMob">149</td><td class="nonMob">128</td><td class="nonMob">217</td><td class="nonMob">575</td><td class="nonMob">745</td><td class="mob">-170</td><td class="mob">575</td><td class="nonMob">30%</td><td class="nonMob">1.16</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">20</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=64" title="West Bromwich Albion All time - Leading Scorers all time stats for Premier League"><img alt="West Bromwich Albion" height="23" src="/img/players_shirt/small/64.png" title="West Bromwich Albion All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>West Bromwich Albion</p></div></a></td><td class="mob">494</td><td class="nonMob">117</td><td class="nonMob">139</td><td class="nonMob">238</td><td class="nonMob">510</td><td class="nonMob">772</td><td class="mob">-262</td><td class="mob">490</td><td class="nonMob">24%</td><td class="nonMob">0.99</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">21</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=187" title="Stoke City All time - Leading Scorers all time stats for Premier League"><img alt="Stoke City" height="23" src="/img/players_shirt/small/187.png" title="Stoke City All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Stoke City</p></div></a></td><td class="mob">380</td><td class="nonMob">116</td><td class="nonMob">109</td><td class="nonMob">155</td><td class="nonMob">398</td><td class="nonMob">525</td><td class="mob">-127</td><td class="mob">457</td><td class="nonMob">31%</td><td class="nonMob">1.2</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">22</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=63" title="Wolverhampton Wanderers All time - Leading Scorers all time stats for Premier League"><img alt="Wolverhampton Wanderers" height="23" src="/img/players_shirt/small/63.png" title="Wolverhampton Wanderers All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Wolverhampton Wanderers</p></div></a></td><td class="mob">378</td><td class="nonMob">114</td><td class="nonMob">93</td><td class="nonMob">171</td><td class="nonMob">408</td><td class="nonMob">580</td><td class="mob">-172</td><td class="mob">435</td><td class="nonMob">30%</td><td class="nonMob">1.15</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">23</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=25" title="Coventry City All time - Leading Scorers all time stats for Premier League"><img alt="Coventry City" height="23" src="/img/players_shirt/small/25.png" title="Coventry City All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Coventry City</p></div></a></td><td class="mob">354</td><td class="nonMob">99</td><td class="nonMob">112</td><td class="nonMob">143</td><td class="nonMob">387</td><td class="nonMob">490</td><td class="mob">-103</td><td class="mob">409</td><td class="nonMob">28%</td><td class="nonMob">1.16</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">24</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=31" title="Norwich City All time - Leading Scorers all time stats for Premier League"><img alt="Norwich City" height="23" src="/img/players_shirt/small/31.png" title="Norwich City All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Norwich City</p></div></a></td><td class="mob">392</td><td class="nonMob">99</td><td class="nonMob">105</td><td class="nonMob">188</td><td class="nonMob">414</td><td class="nonMob">669</td><td class="mob">-255</td><td class="mob">402</td><td class="nonMob">25%</td><td class="nonMob">1.03</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,
 <tr><td class="mob">25</td><td class="mob tdInline"><a href="/alltimestats/AllTimeLeadingScorers?comp_code=EPL&amp;club_id=17" title="Sheffield Wednesday All time - Leading Scorers all time stats for Premier League"><img alt="Sheffield Wednesday" height="23" src="/img/players_shirt/small/17.png" title="Sheffield Wednesday All time - Leading Scorers all time stats for Premier League" width="23"/><div><p>Sheffield Wednesday</p></div></a></td><td class="mob">316</td><td class="nonMob">101</td><td class="nonMob">89</td><td class="nonMob">126</td><td class="nonMob">409</td><td class="nonMob">453</td><td class="mob">-44</td><td class="mob">392</td><td class="nonMob">32%</td><td class="nonMob">1.24</td><td class="mob all"><button class="btn showMob">More</button></td></tr>,

In [7]:
for row in rows[1:]:
    row_data=row.find_all('td')
    row_details=[row1.text.strip() for row1 in row_data[0:12]]
   
    length=len(df)
    df.loc[length]=row_details

In [8]:
df

,#,Clubs,P,W,D,L,F,A,GD,Points,Wins%,Points/Match
0,1,Manchester United,1225,742,269,214,2295,1164,1131,2495,61%,2.04
1,2,Arsenal,1226,671,295,260,2193,1219,974,2308,55%,1.88
2,3,Liverpool,1226,651,301,274,2177,1232,945,2254,53%,1.84
3,4,Chelsea,1225,644,304,277,2081,1231,850,2236,53%,1.83
4,5,Tottenham Hotspur,1225,538,293,394,1884,1559,325,1907,44%,1.56
5,6,Manchester City,1035,526,222,287,1839,1134,705,1800,51%,1.74
6,7,Everton,1226,438,341,447,1563,1587,-24,1647,36%,1.34
7,8,Newcastle United,1107,418,283,406,1523,1506,17,1537,38%,1.39
8,9,Aston Villa,1112,392,310,410,1389,1452,-63,1486,35%,1.34
9,10,West Ham United,1070,359,270,441,1333,1554,-221,1347,34%,1.26
10,11,Southampton,924,280,248,396,1114,1355,-241,1088,30%,1.18
11,12,Blackburn Rovers,696,262,184,250,927,907,20,970,38%,1.39
12,13,Leicester City,650,218,167,265,871,936,-65,821,34%,1.26
13,14,Leeds United,582,223,151,208,793,784,9,820,38%,1.41
14,15,Fulham,644,189,169,286,737,939,-202,736,29%,1.14
15,16,Middlesbrough,574,165,169,240,648,794,-146,661,29%,1.15
16,17,Crystal Palace,576,167,151,258,636,832,-196,652,29%,1.13
17,18,Sunderland,608,153,159,296,612,904,-292,618,25%,1.02
18,19,Bolton Wanderers,494,149,128,217,575,745,-170,575,30%,1.16
19,20,West Bromwich Albion,494,117,139,238,510,772,-262,490,24%,0.99
20,21,Stoke City,380,116,109,155,398,525,-127,457,31%,1.2
21,22,Wolverhampton Wanderers,378,114,93,171,408,580,-172,435,30%,1.15
22,23,Coventry City,354,99,112,143,387,490,-103,409,28%,1.16
23,24,Norwich City,392,99,105,188,414,669,-255,402,25%,1.03
24,25,Sheffield Wednesday,316,101,89,126,409,453,-44,392,32%,1.24
25,26,Milton Keynes Dons,316,99,94,123,384,472,-88,391,31%,1.24
26,27,Charlton Athletic,304,93,82,129,342,442,-100,361,31%,1.19
27,28,Burnley,340,88,85,167,339,529,-190,349,26%,1.03
28,29,Wigan Athletic,304,85,76,143,316,482,-166,331,28%,1.09
29,30,Brighton & Hove Albion,263,78,84,101,315,368,-53,318,30%,1.21
30,31,Swansea City,266,82,66,118,306,383,-77,312,31%,1.17
31,32,Queens Park Rangers,278,81,65,132,339,431,-92,308,29%,1.11
32,33,Nottingham Forest,272,77,79,116,312,418,-106,306,28%,1.13
33,34,Birmingham City,266,73,82,111,273,360,-87,301,27%,1.13
34,35,AFC Bournemouth,264,80,58,126,330,464,-134,298,30%,1.13
35,36,Portsmouth,266,79,65,122,292,380,-88,293,30%,1.1
36,37,Watford,304,73,66,165,310,518,-208,285,24%,0.94
37,38,Derby County,266,68,70,128,271,420,-149,274,26%,1.03
38,39,Sheffield United,234,56,57,121,222,370,-148,225,24%,0.96
39,40,Ipswich Town,202,57,53,92,219,312,-93,224,28%,1.11
40,41,Hull City,190,41,48,101,181,323,-142,171,22%,0.9
41,42,Brentford,112,37,30,45,158,162,-4,141,33%,1.26
42,43,Reading,114,32,23,59,136,186,-50,119,28%,1.04
43,44,Oldham Athletic,84,22,23,39,105,142,-37,89,26%,1.06
44,45,Cardiff City,76,17,13,46,66,143,-77,64,22%,0.84
45,46,Bradford City,76,14,20,42,68,138,-70,62,18%,0.82
46,47,Huddersfield Town,76,12,17,47,50,134,-84,53,16%,0.7
47,48,Blackpool,38,10,9,19,55,78,-23,39,26%,1.03
48,49,Barnsley,38,10,5,23,37,82,-45,35,26%,0.92
49,50,Swindon Town,42,5,15,22,47,100,-53,30,12%,0.71
50,51,Luton Town,36,6,8,22,49,78,-29,26,17%,0.72

In [9]:
df.to_csv(r'C:\Users\mines\Documents\Project\Scraper.csv',index=False)